version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}