apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.3-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/redis"
          name: redis-pv
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pvc